on: [push,workflow_dispatch] # This is a trigger https://docs.github.com/en/actions/reference/events-that-trigger-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Copy scope.txt into vm
      - name: Checkout Repo
        uses: actions/checkout@main

    # Install Golang
      #- uses: actions/checkout@v3
      #- uses: actions/setup-go@v3
      #  with:
      #    go-version: 'stable'
      #- run: go version

      - name: Setup Tools
        run: |
          mkdir -p out/
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.5/subfinder_2.5.5_linux_amd64.zip
          unzip -o subfinder_2.5.5_linux_amd64.zip
          sudo mv subfinder /usr/bin/
          subfinder -version
          wget https://github.com/OWASP/Amass/releases/download/v3.21.2/amass_linux_amd64.zip
          unzip -o amass_linux_amd64.zip
          sudo mv amass_linux_amd64/amass /usr/bin/  
          amass -version
          wget https://github.com/projectdiscovery/httpx/releases/download/v1.2.7/httpx_1.2.7_linux_amd64.zip
          unzip -o httpx_1.2.7_linux_amd64.zip
          sudo mv httpx /usr/bin/  
          httpx -version
          wget https://github.com/projectdiscovery/naabu/releases/download/v2.1.1/naabu_2.1.1_linux_amd64.zip
          unzip -o naabu_2.1.1_linux_amd64.zip
          sudo mv naabu /usr/bin/ 
          naabu -version
          wget https://github.com/projectdiscovery/nuclei/releases/download/v2.8.9/nuclei_2.8.9_linux_amd64.zip
          unzip -o nuclei_2.8.9_linux_amd64.zip
          sudo mv nuclei /usr/bin/  
          nuclei -version 
          mkdir -p ~/nuclei-templates
          nuclei -ut 

      - name: Run Subfinder
        run: |
          mkdir -p out/subfinder-1
          echo "Running Subfinder"
          subfinder -no-color -timeout 20 -silent -dL scope.txt -o out/subfinder-1/output.txt
          echo "Completed Subfinder"
          ls

      - name: Run Amass
        run: |
          echo "Running Amass"
          mkdir -p out/amass-1
          amass enum -passive -timeout 2 -df scope.txt -o out/amass-1/output.txt
          echo "Completed Amass"

      - name: Unique Domains & Sort
        run: |
          mkdir -p out/subdomains/
          cat out/subfinder-1/output.txt out/amass-1/output.txt | sort -n | uniq | tee out/subdomains/subdomains.txt

      - name: Run httpx on subdomains
        run:  |
          echo "Running httpx"
          mkdir -p out/httpx-1
          httpx -l out/subdomains/subdomains.txt -no-color -silent -o out/httpx-1/output.txt
          echo "Completed httpx"

      #- name: Run nuclei on httpx output
      #  run:  |
      #    echo "Running Nuclei"
      #    mkdir -p out/nuclei-1/
      #    #nuclei -list out/httpx-1/output.txt -timeout 2 -t /home/runner/nuclei-templates/cnvd -t /home/runner/nuclei-templates/cves -t /home/runner/nuclei-templates/default-logins -t /home/runner/nuclei-templates/dns -t /home/runner/nuclei-templates/exposures -t /home/runner/nuclei-templates/fuzzing -t /home/runner/nuclei-templates/iot -t /home/runner/nuclei-templates/misconfiguration -t /home/runner/nuclei-templates/takeovers -t /home/runner/nuclei-templates/vulnerabilities -severity critical,high,medium -no-color -silent -output out/nuclei-1/output.txt
      #    echo "Completed Nuclei"

      - name: Save Results
        run: |
          echo "Saving output files to Github Repo"
          #cat out/nuclei-1/output.txt | sort -n | uniq | tee out/nuclei-1/output.txt
          git config --local user.email "jeyaseelans86@gmail.com"
          git config --local user.name "jeyaseelans86"
          git add out/subdomains/subdomains.txt
          #git add out/naabu-1/output.txt
          git add out/httpx-1/output.txt
          #git add out/nuclei-1/output.txt
          git add out/subdomains/subdomains.txt
          git commit -m "Add sorted output" 
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/jeyaseelans86/Asset-Discovery-Actions
